nodeLinker: node-modules

packageExtensions:
  "element-source@0.0.4":
    peerDependencies:
      "@types/react": ">=18.0.0"
      react: ">=17.0.1"
  "react-doctor@0.0.28":
    dependencies:
      "@types/node": "20.19.37"
      eslint: "9.39.4"
